/**
 * Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration:
 * 1. Create a new directory in plugins/ (e.g., plugins/my-integration/)
 * 2. Add your plugin files (index.tsx, steps/, codegen/, etc.)
 * 3. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * To remove an integration:
 * 1. Delete the plugin directory
 * 2. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * Discovered plugins: blockscout, code, data, discord, elizaos, evm-chain, hyperliquid, math, protocol, robinhood, safe, sendgrid, slack, telegram, tempo, web3, webhook
 */

import "./blockscout";
import "./code";
import "./data";
import "./discord";
import "./elizaos";
import "./evm-chain";
import "./hyperliquid";
import "./math";
import "./protocol";
import "./robinhood";
import "./safe";
import "./sendgrid";
import "./slack";
import "./telegram";
import "./tempo";
import "./web3";
import "./webhook";
