export default {
  index: "Overview",
  overview: "Overview",
  web3: "Web3",
  tempo: "Tempo",
  code: "Code",
  math: "Math",
  data: "Data",
  safe: "Safe",
  blockscout: "Blockscout",
  "aave-v3": "Aave V3",
  "aave-v4": "Aave V4",
  aerodrome: "Aerodrome",
  ajna: "Ajna",
  chainlink: "Chainlink",
  chronicle: "Chronicle",
  compound: "Compound V3",
  cowswap: "CoW Swap",
  curve: "Curve",
  ethena: "Ethena",
  "frax-ether-v2": "Frax Ether V2",
  layerzero: "LayerZero",
  lido: "Lido",
  morpho: "Morpho",
  pendle: "Pendle",
  "rocket-pool": "Rocket Pool",
  sky: "Sky",
  spark: "Spark",
  superfluid: "Superfluid",
  uniswap: "Uniswap",
  wrapped: "Wrapped",
  "yearn-v3": "Yearn V3",
  discord: "Discord",
  slack: "Slack",
  telegram: "Telegram",
  sendgrid: "SendGrid",
  webhook: "Webhook",
  hyperliquid: "Hyperliquid",
  robinhood: "Robinhood",
};
